server:
  port: 8085
spring:
  #数据库
  datasource:
    url: jdbc:mysql://${MYSQL-HOST:127.0.0.1}:${MYSQL-PORT:3306}/${MYSQL-DB:jimureport}?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
jeecg :
  # local|minio|alioss
  uploadType: local
  # local
  path :
    #文件路径
    upload: /opt/upload
  # alioss
  oss:
    endpoint: ??
    accessKey: ??
    secretKey: ??
    bucketName: jimureport
  # minio
  minio:
    minio_url: http://minio.jeecg.com
    minio_name: ??
    minio_pass: ??
    bucketName: ??
  #大屏报表参数设置
  jmreport:
    #只看自己的数据
    saas: false
    #是否开启租户模式 Support By v1.5.5+
    openTenant: true
    #安全模式(敏感接口校验、saas模式下不允许使用平台数据源)
    #safeMode: true
    # 列索引
    col: 100
    #接口超时设置（毫秒）
    connect-timeout: 300000
    pageSize:
      - 10
      - 20
      - 30
      - 40
#输出sql日志
logging:
  level:
    org.jeecg.modules.jmreport : info
